
INSERT INTO public.site_settings (key, value) VALUES
  ('company_name_ar', 'آل شريف لنظم الري الحديث'),
  ('company_name_en', 'Al Sherif Modern Irrigation Systems'),
  ('company_tagline', 'شريكك الأمثل في حلول الري الحديث'),
  ('company_description', 'شركة هندسية متخصصة في تصميم وتوريد وتركيب أنظمة الري الحديث للمزارع والمشاريع الزراعية الكبرى.'),
  ('logo_url', ''),
  ('favicon_url', ''),
  ('phone1', '01111661177'),
  ('phone1_label', 'م. عادل شريف — المدير العام'),
  ('phone2', '01122811500'),
  ('phone2_label', 'م. إيهاب — قسم المبيعات'),
  ('whatsapp', '201028200048'),
  ('admin_phone', '01028200048'),
  ('email', 'info@alsherif-irrigation.com'),
  ('email2', ''),
  ('address', 'الشعراوي، قطاع غرب النوبارية، مركز حوش عيسى، محافظة البحيرة، مصر'),
  ('postal_code', '5820220'),
  ('plus_code', 'P726+RV2'),
  ('hours', 'السبت - الخميس: 9 صباحاً - 6 مساءً'),
  ('hours_off', 'الجمعة: إجازة'),
  ('google_map_embed', 'https://www.google.com/maps?q=P726%2BRV2%20Al%20Shaarawy%20Hosh%20Eissa%20Beheira%20Egypt&output=embed'),
  ('google_map_link', 'https://www.google.com/maps/search/?api=1&query=P726%2BRV2+Al+Shaarawy+Hosh+Eissa+Beheira+Egypt'),
  ('social_facebook', ''),
  ('social_instagram', ''),
  ('social_youtube', ''),
  ('social_linkedin', ''),
  ('social_x', ''),
  ('social_tiktok', ''),
  ('hero_title', 'نُصمّم أنظمة الري'),
  ('hero_title_accent', 'لأرضٍ أكثر إنتاجاً'),
  ('hero_subtitle', 'حلول متكاملة من الاستشارة الهندسية وحتى التركيب والصيانة — نخدم المزارعين وشركات المقاولات الزراعية والموزعين بأنظمة ري حديثة ومنتجات معتمدة عالمياً.'),
  ('hero_badge', 'الشريك الهندسي لمشاريع الري في مصر'),
  ('stats_years', '+25'),
  ('stats_projects', '+500'),
  ('stats_governorates', '18'),
  ('stats_clients', '+2,400'),
  ('footer_about', 'شركة هندسية متخصصة في تصميم وتوريد وتركيب أنظمة الري الحديث للمزارع والمشاريع الزراعية الكبرى.'),
  ('seo_title', 'آل شريف لنظم الري الحديث - Al Sherif Modern Irrigation Systems'),
  ('seo_description', 'حلول متكاملة لأنظمة الري الحديث في مصر — تصميم وتوريد وتركيب وصيانة أنظمة الري بالتنقيط والرش والمحوري بأعلى جودة.'),
  ('seo_keywords', 'أنظمة الري, الري الحديث, الري بالتنقيط, آل شريف, مصر, الري بالرش, معدات زراعية')
ON CONFLICT (key) DO NOTHING;
